version: 2.1
orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - run:
          command:
                  sleep 540s
          name: Test1
      - run:
         command: sleep 540s
         name: Test2
      - run:
         command: sleep 540s
         name: Test2

      - run:
          command:
                  sleep 540s
          name: Test1
      - run:
         command: sleep 540s
         name: Test2

      - run:
          command:
                  sleep 540s
          name: Test1
      - run:
         command: sleep 540s
         name: Test2

      - run:
          command:
                  sleep 540s
          name: Test1
      - run:
         command: sleep 540s
         name: Test2

      - run:
          command:
                  sleep 540s
          name: Test1
      - run:
         command: sleep 540s
         name: Test2

      - run:
          command:
                  sleep 540s
          name: Test1
      - run:
         command: sleep 540s
         name: Test2

      - run:
          command:
                  sleep 540s
          name: Test1
      - run:
         command: sleep 540s
         name: Test2

      - run:
          command:
                  sleep 540s
          name: Test1
      - run:
         command: sleep 540s
         name: Test2

      - run:
          command:
                  sleep 540s
          name: Test1
      - run:
         command: sleep 540s
         name: Test2

      - run:
          command:
                  sleep 540s
          name: Test1
      - run:
         command: sleep 540s
         name: Test2

      - run:
          command:
                  sleep 540s
          name: Test1
      - run:
         command: sleep 540s
         name: Test2

      - run:
          command:
                  sleep 540s
          name: Test1
      - run:
         command: sleep 540s
         name: Test2

      - run:
          command:
                  sleep 540s
          name: Test1
      - run:
         command: sleep 540s
         name: Test2

      - run:
          command:
                  sleep 540s
          name: Test1
      - run:
         command: sleep 540s
         name: Test2

      - run:
          command:
                  sleep 540s
          name: Test1
      - run:
         command: sleep 540s
         name: Test2

      - run:
          command:
                  sleep 540s
          name: Test1
      - run:
         command: sleep 540s
         name: Test2

      - run:
          command:
                  sleep 540s
          name: Test1
      - run:
         command: sleep 540s
         name: Test2

      - run:
          command:
                  sleep 540s
          name: Test1
      - run:
         command: sleep 540s
         name: Test2

      - run:
          command:
                  sleep 540s
          name: Test1
      - run:
         command: sleep 540s
         name: Test2

      - run:
          command:
                  sleep 540s
          name: Test1
      - run:
         command: sleep 540s
         name: Test2

      - run:
          command:
                  sleep 540s
          name: Test1
      - run:
         command: sleep 540s
         name: Test2

      - run:
          command:
                  sleep 540s
          name: Test1
      - run:
         command: sleep 540s
         name: Test2

      - run:
          command:
                  sleep 540s
          name: Test1
      - run:
         command: sleep 540s
         name: Test2

      - run:
          command:
                  sleep 540s
          name: Test1
      - run:
         command: sleep 540s
         name: Test2

      - run:
          command:
                  sleep 540s
          name: Test1
      - run:
         command: sleep 540s
         name: Test2

      - run:
          command:
                  sleep 540s
          name: Test1
      - run:
         command: sleep 540s
         name: Test2

      - run:
          command:
                  sleep 540s
          name: Test1
      - run:
         command: sleep 540s
         name: Test2

      - run:
          command:
                  sleep 540s
          name: Test1
      - run:
         command: sleep 540s
         name: Test2

      - run:
          command:
                  sleep 540s
          name: Test1
      - run:
         command: sleep 540s
         name: Test2

      - run:
          command:
                  sleep 540s
          name: Test1
      - run:
         command: sleep 540s
         name: Test2

      - run:
          command:
                  sleep 540s
          name: Test1
      - run:
         command: sleep 540s
         name: Test2

      - run:
          command:
                  sleep 540s
          name: Test1
      - run:
         command: sleep 540s
         name: Test2


workflows:
  main:
    jobs:
      - build-and-test
